/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an owner or consumer account and sign in. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description The request is invalid. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The request conflicts with the current state. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange email and password for a JWT. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description The request is invalid. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The request conflicts with the current state. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserDto"];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Keys assigned to the signed-in consumer, with limits and this month's quota consumption. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MyKeyDto"][];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The consumer's own usage: totals by outcome and a time series. */
        get: {
            parameters: {
                query?: {
                    /** @description Start of the range (ISO 8601). Defaults to 24 hours before to. */
                    from?: string;
                    /** @description End of the range (ISO 8601). Defaults to now. */
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsageReportDto"];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Credit balance, credits spent this month and recent top-ups. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreditAccountDto"];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/credits/top-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add credits. This is a mock purchase: no payment is taken. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TopUpRequest"];
                    "text/json": components["schemas"]["TopUpRequest"];
                    "application/*+json": components["schemas"]["TopUpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreditAccountDto"];
                    };
                };
                /** @description The request is invalid. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The request conflicts with the current state. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usage across the owner's APIs: totals by outcome, a time series and a per-consumer breakdown. */
        get: {
            parameters: {
                query?: {
                    /** @description Narrow the report to one API. */
                    apiId?: string;
                    /** @description Start of the range (ISO 8601). Defaults to 24 hours before to. */
                    from?: string;
                    /** @description End of the range (ISO 8601). Defaults to now. */
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OwnerAnalyticsDto"];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consumers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consumer accounts that can be given a key, with how many active keys each holds on the owner's APIs. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConsumerDto"][];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apis/{apiId}/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    apiId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiKeyDto"][];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The resource does not exist or belongs to someone else. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /** Issue a key to a consumer at a tier. The secret is returned only in this response. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    apiId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateApiKeyRequest"];
                    "text/json": components["schemas"]["CreateApiKeyRequest"];
                    "application/*+json": components["schemas"]["CreateApiKeyRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatedApiKeyDto"];
                    };
                };
                /** @description The request is invalid. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The resource does not exist or belongs to someone else. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The request conflicts with the current state. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apis/{apiId}/keys/{keyId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Permanently revoke a key. Takes effect on the next gateway request. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    apiId: string;
                    keyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiKeyDto"];
                    };
                };
                /** @description The request is invalid. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The resource does not exist or belongs to someone else. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The request conflicts with the current state. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** APIs registered by the signed-in owner. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiDto"][];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /** Register an upstream API. It becomes reachable at `/gw/{slug}/...`. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateApiRequest"];
                    "text/json": components["schemas"]["CreateApiRequest"];
                    "application/*+json": components["schemas"]["CreateApiRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiDto"];
                    };
                };
                /** @description The request is invalid. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The request conflicts with the current state. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apis/{apiId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    apiId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiDto"];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The resource does not exist or belongs to someone else. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    apiId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateApiRequest"];
                    "text/json": components["schemas"]["UpdateApiRequest"];
                    "application/*+json": components["schemas"]["UpdateApiRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiDto"];
                    };
                };
                /** @description The request is invalid. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The resource does not exist or belongs to someone else. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The request conflicts with the current state. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        /** Delete an API together with its tiers, keys and webhooks. Usage history is kept. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    apiId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The request is invalid. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The resource does not exist or belongs to someone else. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The request conflicts with the current state. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apis/{apiId}/tiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    apiId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TierDto"][];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The resource does not exist or belongs to someone else. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /** Define an access tier: requests per minute, monthly quota and credit cost per request. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    apiId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TierRequest"];
                    "text/json": components["schemas"]["TierRequest"];
                    "application/*+json": components["schemas"]["TierRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TierDto"];
                    };
                };
                /** @description The request is invalid. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The resource does not exist or belongs to someone else. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The request conflicts with the current state. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apis/{apiId}/tiers/{tierId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change a tier. New limits apply to its keys from the next request. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    apiId: string;
                    tierId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TierRequest"];
                    "text/json": components["schemas"]["TierRequest"];
                    "application/*+json": components["schemas"]["TierRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TierDto"];
                    };
                };
                /** @description The request is invalid. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The resource does not exist or belongs to someone else. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The request conflicts with the current state. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a tier. Refused while keys are still assigned to it. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    apiId: string;
                    tierId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The request is invalid. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The resource does not exist or belongs to someone else. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The request conflicts with the current state. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apis/{apiId}/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    apiId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookDto"][];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The resource does not exist or belongs to someone else. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /** Subscribe a URL to quota events (`quota.threshold_reached`, `quota.exceeded`) of this API. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    apiId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["WebhookRequest"];
                    "text/json": components["schemas"]["WebhookRequest"];
                    "application/*+json": components["schemas"]["WebhookRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookDto"];
                    };
                };
                /** @description The request is invalid. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The resource does not exist or belongs to someone else. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The request conflicts with the current state. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apis/{apiId}/webhooks/{webhookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    apiId: string;
                    webhookId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["WebhookRequest"];
                    "text/json": components["schemas"]["WebhookRequest"];
                    "application/*+json": components["schemas"]["WebhookRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookDto"];
                    };
                };
                /** @description The request is invalid. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The resource does not exist or belongs to someone else. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The request conflicts with the current state. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    apiId: string;
                    webhookId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The request is invalid. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The resource does not exist or belongs to someone else. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The request conflicts with the current state. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apis/{apiId}/webhooks/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The most recent delivery attempts for this API's webhooks, newest first. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    apiId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookDeliveryDto"][];
                    };
                };
                /** @description Missing, expired or invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The signed-in user's role may not call this endpoint. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The resource does not exist or belongs to someone else. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description: string | null;
            targetBaseUrl: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        ApiKeyDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            apiId: string;
            name: string;
            keyPrefix: string;
            status: components["schemas"]["ApiKeyStatus"];
            /** Format: uuid */
            tierId: string;
            tierName: string;
            /** Format: uuid */
            consumerId: string;
            consumerName: string;
            consumerEmail: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            revokedAt: string | null;
        };
        /** @enum {string} */
        ApiKeyStatus: "Active" | "Revoked";
        AuthResponse: {
            accessToken: string;
            /** Format: date-time */
            expiresAt: string;
            user: components["schemas"]["UserDto"];
        };
        ConsumerDto: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
            /** Format: int32 */
            activeKeyCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        ConsumerUsageDto: {
            /** Format: uuid */
            consumerId: string;
            name: string;
            email: string;
            usage: components["schemas"]["UsageSummaryDto"];
        };
        CountDto: {
            label: string;
            /** Format: int64 */
            requests: number;
        };
        CreateApiKeyRequest: {
            name: string;
            /** Format: uuid */
            tierId: string;
            consumerEmail: string;
        };
        CreateApiRequest: {
            name: string;
            slug: string | null;
            description: string | null;
            targetBaseUrl: string;
        };
        CreatedApiKeyDto: {
            key: components["schemas"]["ApiKeyDto"];
            secret: string;
        };
        CreditAccountDto: {
            /** Format: double */
            balance: number;
            /** Format: double */
            spentThisMonth: number;
            transactions: components["schemas"]["CreditTransactionDto"][];
        };
        CreditTransactionDto: {
            /** Format: uuid */
            id: string;
            /** Format: double */
            amount: number;
            type: components["schemas"]["CreditTransactionType"];
            description: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {string} */
        CreditTransactionType: "TopUp";
        /** @enum {string} */
        DayOfWeek: "Sunday" | "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday";
        HeatmapCellDto: {
            dayOfWeek: components["schemas"]["DayOfWeek"];
            /** Format: int32 */
            hour: number;
            /** Format: int64 */
            requests: number;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        MyKeyDto: {
            /** Format: uuid */
            id: string;
            name: string;
            keyPrefix: string;
            status: components["schemas"]["ApiKeyStatus"];
            apiName: string;
            apiSlug: string;
            tierName: string;
            /** Format: int32 */
            requestsPerMinute: number;
            /** Format: int32 */
            monthlyQuota: number;
            /** Format: double */
            creditCostPerRequest: number;
            /** Format: int64 */
            quotaUsed: number;
            /** Format: int64 */
            quotaRemaining: number;
            /** Format: date-time */
            createdAt: string;
        };
        OwnerAnalyticsDto: {
            report: components["schemas"]["UsageReportDto"];
            consumers: components["schemas"]["ConsumerUsageDto"][];
        };
        ProblemDetails: {
            type: string | null;
            title: string | null;
            /** Format: int32 */
            status: number | null;
            detail: string | null;
            instance: string | null;
        } & {
            [key: string]: unknown;
        };
        RegisterRequest: {
            name: string;
            email: string;
            password: string;
            role: components["schemas"]["UserRole"];
        };
        TierDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            apiId: string;
            name: string;
            /** Format: int32 */
            requestsPerMinute: number;
            /** Format: int32 */
            monthlyQuota: number;
            /** Format: double */
            creditCostPerRequest: number;
            /** Format: date-time */
            createdAt: string;
        };
        TierRequest: {
            name: string;
            /** Format: int32 */
            requestsPerMinute: number;
            /** Format: int32 */
            monthlyQuota: number;
            /** Format: double */
            creditCostPerRequest: number;
        };
        TopUpRequest: {
            /** Format: double */
            amount: number;
        };
        UpdateApiRequest: {
            name: string;
            description: string | null;
            targetBaseUrl: string;
            isActive: boolean;
        };
        UsageBreakdownDto: {
            statusCodes: components["schemas"]["CountDto"][];
            methods: components["schemas"]["CountDto"][];
            endpoints: components["schemas"]["CountDto"][];
            latencyBuckets: components["schemas"]["CountDto"][];
            apis: components["schemas"]["CountDto"][];
            tiers: components["schemas"]["CountDto"][];
            heatmap: components["schemas"]["HeatmapCellDto"][];
        };
        UsagePointDto: {
            /** Format: date-time */
            bucketStart: string;
            usage: components["schemas"]["UsageSummaryDto"];
            /** Format: double */
            averageLatencyMs: number;
        };
        UsageReportDto: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            /** Format: int32 */
            bucketMinutes: number;
            summary: components["schemas"]["UsageSummaryDto"];
            /** Format: double */
            averageLatencyMs: number;
            series: components["schemas"]["UsagePointDto"][];
            breakdown: components["schemas"]["UsageBreakdownDto"];
        };
        UsageSummaryDto: {
            /** Format: int64 */
            totalRequests: number;
            /** Format: int64 */
            successful: number;
            /** Format: int64 */
            failed: number;
            /** Format: int64 */
            rateLimited: number;
            /** Format: int64 */
            quotaExceeded: number;
            /** Format: int64 */
            insufficientCredits: number;
            /** Format: double */
            creditsConsumed: number;
        };
        UserDto: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
            role: components["schemas"]["UserRole"];
            /** Format: double */
            creditBalance: number;
        };
        /** @enum {string} */
        UserRole: "Owner" | "Consumer";
        WebhookDeliveryDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            subscriptionId: string;
            eventType: string;
            url: string;
            /** Format: int32 */
            responseStatus: number | null;
            success: boolean;
            /** Format: int32 */
            attempts: number;
            error: string | null;
            payload: string;
            /** Format: date-time */
            createdAt: string;
        };
        WebhookDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            apiId: string;
            url: string;
            secret: string;
            /** Format: int32 */
            thresholdPercent: number;
            events: string[];
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        WebhookRequest: {
            url: string;
            /** Format: int32 */
            thresholdPercent: number;
            events: string[];
            isActive: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
